font:
  normal:
    family: Lilex
    style: Regular

  bold:
    family: Lilex
    style: Bold

  italic:
    family: Lilex
    style: Italic

  bold_italic:
    family: Lilex
    style: Bold Italic

  size: 11

window:
  # Window dimensions in character columns and lines
  # (changes require restart)
  dimensions:
    columns: 0
    lines: 0

  # Window position (changes require restart)
  #
  # Specified in number of pixels.
  # If the position is not set, the window manager will handle the placement.
  #position:
  #  x: 0
  #  y: 0

  # Adds this many blank pixels of padding around the window
  # Units are physical pixels; this is not DPI aware.
  # (change requires restart)
  padding:
    x: 2
    y: 2

  # Spread additional padding evenly around the terminal content.
  dynamic_padding: false

  # Values for `decorations`:
  #- full: Borders and title bar
  #- none: Neither borders nor title bar
  #- buttonless: Title bar, transparent background and title bar buttons
  #- transparent: Title bar, transparent background, but no title bar buttons
  decorations: none

  # When true, alacritty starts maximized.
  startup_mode: Windowed

  # Window title
  #title: Alacritty

