# ~/.config/starship.toml
[character]
success_symbol = "[Œª](bold green)"
error_symbol = "[Œª](bold red)"

[directory]
truncation_length = 10
truncate_to_repo = true
format = "[$path]($style)[$lock_symbol]($lock_style) "
style = "bold italic #87A752"

[git_branch]
format = " [$symbol$branch]($style) "

[golang]
format = "via [Ô≥ë $version](208 bold) "

[directory.substitutions]
"~" = "üè†"
